"""add title column in Role table

Revision ID: a9be06f116b3
Revises: 051d061e83c1
Create Date: 2026-09-15 20:54:21.343145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9be06f116b3'
down_revision: Union[str, Sequence[str], None] = '051d061e83c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'title')
    # ### end Alembic commands ###
